development:
  adapter: mysql2
  database: spotapartner_staging
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: spotapartner_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: spotapartner_staging
  username: root
  password:
  encoding: utf8